#!/usr/bin/env bash

set -e
DATE=$(date +%m%d_%H%M%S)
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &>/dev/null && pwd )"
cd "$SCRIPT_DIR"

source env.sh
cd ..

echo $INIT
ssh $REMOTE_HOST "cd /root/remote/$PROJECT;
                  /usr/lib/qt6/bin/qmlls --build-dir /root/remote/.build/$PROJECT \
                        --no-cmake-calls \
                        $@"
